# Generated by Django 4.1 on 2022-09-29 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookie',
            name='cookie_size',
        ),
        migrations.RemoveField(
            model_name='cookie',
            name='cookie_type',
        ),
    ]
