# Generated by Django 4.1 on 2022-11-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_cookie_cookie_size_remove_cookie_cookie_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieDbTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(max_length=30)),
                ('Platform', models.CharField(max_length=30)),
                ('Category', models.CharField(max_length=30)),
                ('Cookie_or_Data_Key_name_Domain_Description', models.CharField(max_length=30)),
                ('Retention_period', models.CharField(max_length=30)),
                ('Data_ControllerUser_Privacy_and_GDPR_Rights_Portals', models.CharField(max_length=30)),
                ('Wildcard_match', models.CharField(max_length=30)),
            ],
        ),
    ]
